// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMn4KLKv65G-C5jYSKJfgx2OKrhsgSOJU',
    appId: '1:961239095370:web:bb7d602f0105c67513aeb3',
    messagingSenderId: '961239095370',
    projectId: 'insideoutprac-project',
    authDomain: 'insideoutprac-project.firebaseapp.com',
    storageBucket: 'insideoutprac-project.firebasestorage.app',
    measurementId: 'G-VESNNNJB2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvrqi8ooKHXJIXOUeUB9ucryNdoT0uXGY',
    appId: '1:961239095370:android:1d8d202415ec888113aeb3',
    messagingSenderId: '961239095370',
    projectId: 'insideoutprac-project',
    storageBucket: 'insideoutprac-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG14f8XLQf1oyJ-T-GxH3fD-opePWpCPg',
    appId: '1:961239095370:ios:2089e83a3e44dd4e13aeb3',
    messagingSenderId: '961239095370',
    projectId: 'insideoutprac-project',
    storageBucket: 'insideoutprac-project.firebasestorage.app',
    iosBundleId: 'com.example.firebaseprac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG14f8XLQf1oyJ-T-GxH3fD-opePWpCPg',
    appId: '1:961239095370:ios:2089e83a3e44dd4e13aeb3',
    messagingSenderId: '961239095370',
    projectId: 'insideoutprac-project',
    storageBucket: 'insideoutprac-project.firebasestorage.app',
    iosBundleId: 'com.example.firebaseprac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMn4KLKv65G-C5jYSKJfgx2OKrhsgSOJU',
    appId: '1:961239095370:web:d1afda2f68aaab3313aeb3',
    messagingSenderId: '961239095370',
    projectId: 'insideoutprac-project',
    authDomain: 'insideoutprac-project.firebaseapp.com',
    storageBucket: 'insideoutprac-project.firebasestorage.app',
    measurementId: 'G-QYTMBSHHLC',
  );
}
